// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtQZLyNMhyr0OtOkf6MrY_8L-Mj-_OB2o',
    appId: '1:201603409305:web:4eccf055b136da23e35f08',
    messagingSenderId: '201603409305',
    projectId: 'todolist-f8f62',
    authDomain: 'todolist-f8f62.firebaseapp.com',
    storageBucket: 'todolist-f8f62.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4dvpj34emtOM88T_J-vrqyAp3bQQZcF8',
    appId: '1:201603409305:android:70dbdbf7f36b6c10e35f08',
    messagingSenderId: '201603409305',
    projectId: 'todolist-f8f62',
    storageBucket: 'todolist-f8f62.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwqzF8S2Yi2kk5Q4kRd9-E6SN6MH6S7Fw',
    appId: '1:201603409305:ios:250736fed120ccffe35f08',
    messagingSenderId: '201603409305',
    projectId: 'todolist-f8f62',
    storageBucket: 'todolist-f8f62.appspot.com',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwqzF8S2Yi2kk5Q4kRd9-E6SN6MH6S7Fw',
    appId: '1:201603409305:ios:250736fed120ccffe35f08',
    messagingSenderId: '201603409305',
    projectId: 'todolist-f8f62',
    storageBucket: 'todolist-f8f62.appspot.com',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtQZLyNMhyr0OtOkf6MrY_8L-Mj-_OB2o',
    appId: '1:201603409305:web:d1d84e52df247263e35f08',
    messagingSenderId: '201603409305',
    projectId: 'todolist-f8f62',
    authDomain: 'todolist-f8f62.firebaseapp.com',
    storageBucket: 'todolist-f8f62.appspot.com',
  );
}
